if(TARGET OpenSSL::SSL)
  message(STATUS "Using existing OpenSSL::SSL target.")
else()
  if(HUNTER_ENABLED)
    hunter_add_package(OpenSSL)
    find_package(OpenSSL REQUIRED)
  else()
    find_package(OpenSSL)
    if(NOT OPENSSL_FOUND)
      message(FATAL_ERROR "Could not find OpenSSL and Hunter is disabled")
    endif()
  endif()
endif()
